In [24]:
import numpy as np

arr = np.array([[1,2,3,4,5,6],[0,1,2,3,4,5],[7,8,9,0,1,2]]) #3x6
arr2 = [1,2,3]
arr3 = arr[np.arange(3),arr2]
print(arr3)

[2 2 0]


In [31]:
print(arr3.reshape(3,1))

[[2]
 [2]
 [0]]


In [3]:
import numpy as np
arr4 = np.array([
    [1,1,0,0],
    [0,0,1,0],
    [0,0,0,1],
    [2,1,0,0]
])
arr5 = np.zeros_like(arr4)
arr5[arr4>0] = 4
print(np.sum(arr4,axis=1))

[2 1 1 3]
